### PR TITLE
Add lockfile as dependency

### PR DESCRIPTION
**Pull request by maresb**
Fixes <https://github.com/conda/conda-lock/issues/265#issuecomment-1410206650>

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
This seems like a pretty heavy hammer, bringing in two optional dependencies to meet some n-level deep optional dependency... is there no way this can be fixed on the respective upstream feedstocks?

**Comment by maresb** [comment]
Agreed. The lack of a cachecontrol v0.13 release seems to be the source of the headaches, but there has been no response on the issue for several months. Do you have any concrete ideas for how to fix it in the upstream feedstocks?

**Comment by bollwyvl** [comment]
Perhaps this: https://github.com/conda-forge/cachecontrol-feedstock/pull/16

Then, whenever 0.13 does roll around, it would presumably switch the dependency.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please restart ci

**Review by bollwyvl — APPROVED** [review]
I'm happy to merge this if @maresb is cool with the change. i guess it keeps folk from using older `cachecontrol` unless we do some backports...

**Comment by maresb** [comment]
Yes, this is excellent. Thanks!!!

**Pull request merged**
