### PR TITLE
Changed doc_url

### PR DESCRIPTION
**Pull request by tdejager**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The previous doc_url returned a 404 when browsing to the docmentation, I've updated it with what I think is the correct URL. At [Prefix.dev conda-lock](https://prefix.dev/channels/conda-forge/packages/conda-lock) we use this to show the different url's on the page. That's how I found out :)

### CODE REVIEW

**Comment by tdejager** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Thanks for the update.

Working upstream on the test fail: in the meantime, could you also check the other urls (e.g `dev_url`)?

**Comment by bollwyvl** [comment]
Got that in upstream: i'll update the urls to trigger CI...

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Thanks!

**Comment by tdejager** [comment]
Thanks for merging!

**Pull request merged**
